pipeline {
  environment {
    registry = "wadapad/cicd-jenkins"
    docreds = 'dockerhub_id'
    dockerImage = ''
  }
  agent any
  tools {nodejs "NODEJS"}
  stages {
    stage('main logo prepare') {
      when {
        branch "main"
      }
      steps {
        sh 'mv ./jenkins/main.svg ./src/logo.svg'
      }
    }
    stage('dev logo prepare') {
      when {
        branch "dev"
      }
      steps {
        script {
          env.PORT=3001
        }
        sh 'mv ./jenkins/dev.svg ./src/logo.svg'
      }
    }
    stage('build') {
      steps {
        sh 'npm install'
        sh 'npm run build'
      }
    }
    stage('test') {
      steps {
        sh 'npm run test'
      }
    }
    stage('imagebuild') {
			steps {
        script {
          dockerImage = docker.build registry + "${BUILD_ID}"
        }
			}
    }
    stage('deploy') {
      steps {
        script {
            docker.withRegistry('', docreds)
            {
              dockerImage.push() 
            }
        }
      }
    }
  }
}
