pipeline {
  agent any
  tools {nodejs "NODEJS"}
  stages {
    stage('main logo prepare') {
      when {
        branch "main"
      }
      steps {
        sh 'mv ./jenkins/main.svg ./src/logo.svg'
      }
    }
    stage('dev logo prepare') {
      when {
        branch "dev"
      }
      steps {
        script {
          env.PORT=3001
        }
        sh 'mv ./jenkins/dev.svg ./src/logo.svg'
      }
    }
    stage('build') {
      steps {
        sh 'npm install'
        sh 'npm run build'
      }
    }
    stage('test') {
      steps {
        sh 'npm run test'
      }
    }
    stage('imagebuild') {
      steps {
        echo 'Building docker image...'
      }
    }
    stage('deploy') {
      steps {
        sh 'npm start &'
        sh 'sleep 1'
        sh 'echo $! > .pidfile'
        input message: 'Finished?'
        sh 'kill $(cat .pidfile)'
      }
    }
  }
}
