pipeline {
  agent any
  tools {nodejs "NODEJS"}
  stages {
    stage('main logo prepare') {
      when {
        branch "main"
      }
      steps {
        sh 'chmod +x ./jenkins/deliver.sh'
        sh './jenkins/copylogo.sh main'
      }
    }
    stage('dev logo prepare') {
      when {
        branch "dev"
      }
      steps {
        sh 'chmod +x ./jenkins/deliver.sh'
        sh './jenkins/copylogo.sh dev'
      }
    }
    stage('build') {
      steps {
        sh 'npm install'
      }
    }
    stage('test') {
      steps {
        sh 'chmod +x ./jenkins/deliver.sh'
        sh 'chmod +x ./jenkins/kill.sh'
        sh './jenkins/deliver.sh'
        input message: 'Finished?'
        sh './jenkins/kill.sh'
      }
    }
    stage('imagebuild') {
      steps {
        echo 'Building docker image...'
      }
    }
    stage('deploy') {
      steps {
        echo 'Deploying...'
      }
    }
  }
}
